#ifndef MECHANICAL_MOTION_PROFILE_H
#define MECHANICAL_MOTION_PROFILE_H

#include <stdint.h>

/* Generated by tools/mechanical_motion_sim.py; verify on hardware at low speed. */
typedef struct {
    float angle_deg;
    uint32_t duration_ms;
    uint8_t waypoint;
} MechanicalMotionStep;

static const MechanicalMotionStep kMechanicalMotionProfile[] = {
    { 7.4677f, 223U, 0U }, /* leg1_drive */
    { -2.2530f, 347U, 0U }, /* leg1_brake */
    { 0.0000f, 302U, 1U }, /* leg1_settle */
    { -3.6960f, 696U, 0U }, /* leg2_drive */
    { 2.9993f, 370U, 0U }, /* leg2_brake */
    { 0.0000f, 521U, 2U }, /* leg2_settle */
};

#define MECHANICAL_MOTION_PROFILE_COUNT (sizeof(kMechanicalMotionProfile) / sizeof(kMechanicalMotionProfile[0]))

#endif
