#include "Drive.h"
uint8_t left, mid, right;
static volatile uint8_t s_left_duty_percent;
static volatile uint8_t s_right_duty_percent;

void motor_left_forward(void) {
    DL_GPIO_setPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_17_PIN);
    DL_GPIO_clearPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_16_PIN);
}

void motor_left_backward(void) {
    DL_GPIO_clearPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_17_PIN);
    DL_GPIO_setPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_16_PIN);
}

void motor_left_stop(void) {
    s_left_duty_percent = 0U;
    DL_GPIO_clearPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_16_PIN | GPIO_Drive_A_PINA_17_PIN);
}

void motor_right_forward(void) {
    DL_GPIO_clearPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_4_PIN);
    DL_GPIO_setPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_1_PIN);
}

void motor_right_backward(void) {
    DL_GPIO_setPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_4_PIN);
    DL_GPIO_clearPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_1_PIN);
}

void motor_right_stop(void) {
    s_right_duty_percent = 0U;
    DL_GPIO_clearPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_1_PIN | GPIO_Drive_B_PINB_4_PIN);
}

void set_motor_speed(float left_duty, float right_duty) {
    uint32_t L, R;

    if (left_duty < 0.0f) left_duty = 0.0f;
    if (left_duty > 100.0f) left_duty = 100.0f;
    if (right_duty < 0.0f) right_duty = 0.0f;
    if (right_duty > 100.0f) right_duty = 100.0f;

    s_left_duty_percent = (uint8_t)(left_duty + 0.5f);
    s_right_duty_percent = (uint8_t)(right_duty + 0.5f);

    /*
     * Keep the fractional duty generated by the 1 ms ramp.  The old uint32_t
     * interface rounded every command to a whole percent and made low-speed
     * changes visibly step-shaped.
     */
    L = (uint32_t)(left_duty * 32.0f + 0.5f);
    R = (uint32_t)(right_duty * 32.0f + 0.5f);
    DL_Timer_setCaptureCompareValue(PWM_A_INST, L , GPIO_PWM_A_C0_IDX );
    DL_Timer_setCaptureCompareValue(PWM_B_INST, R , GPIO_PWM_B_C1_IDX);
}

uint8_t Drive_GetLeftDutyPercent(void)
{
    return s_left_duty_percent;
}

uint8_t Drive_GetRightDutyPercent(void)
{
    return s_right_duty_percent;
}

void PWM_D0(double Compare)
{
	DL_Timer_setCaptureCompareValue(PWM_A_INST, 3200-Compare, GPIO_PWM_A_C0_IDX);
}

void PWM_D1(double Compare)
{
	DL_Timer_setCaptureCompareValue(PWM_B_INST, 3200-Compare, GPIO_PWM_B_C1_IDX);
}

void Car_Move(double PL,double PR)
{
	if(PR==0){PWM_D0(0);DL_GPIO_clearPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_17_PIN);DL_GPIO_clearPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_16_PIN);}
	if(PR<0){PWM_D0(-PR);DL_GPIO_clearPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_17_PIN);DL_GPIO_setPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_16_PIN);}
	if(PR>0){PWM_D0(PR);DL_GPIO_clearPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_16_PIN);DL_GPIO_setPins(GPIO_Drive_A_PORT, GPIO_Drive_A_PINA_17_PIN);}

	if(PL==0){PWM_D1(0);DL_GPIO_clearPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_4_PIN);DL_GPIO_clearPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_1_PIN);}
	if(PL<0){PWM_D1(-PL);DL_GPIO_clearPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_1_PIN);DL_GPIO_setPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_4_PIN);}
	if(PL>0){PWM_D1(PL);DL_GPIO_clearPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_4_PIN);DL_GPIO_setPins(GPIO_Drive_B_PORT, GPIO_Drive_B_PINB_1_PIN);}
}
